---
title: "Introduction"
author: "Michael Flynn"
date: "`r Sys.Date()'"
output:
  html_document:
    df_print: paged
bibliography: "/Chapters/one.bib"
editor_options: 
  markdown: 
    wrap: 72
---


# Front Matter

This section loads the data files and libraries. Assembles the main data

```{r setup , echo = FALSE, include = FALSE}

library(tidyverse)
library(tidyr)
library(broom)
library(broom.mixed)
library(psych)
library(ipw)
library(modelr)
library(cshapes)
library(maps)
library(countrycode)
library(dagitty)
library(ggdag)
library(arm)
library(brms)
library(rstan)
library(cmdstanr)
library(parallel)
library(tidybayes)
library(scales)
library(ggdist)
library(kableExtra)
library(BayesPostEst)
library(texreg)
library(modelsummary)
library(gt)
library(webshot)
library(kableExtra)
library(ggExtra)
library(ggmcmc)
library(ggpubr)
library(patchwork)
library(here)
library(arm)
library(performance)
library(ROCR)
library(tictoc)
library(remotes)
library(sf)
library(rnaturalearth)
library(rworldmap)

knitr::opts_chunk$set(comment = '', dpi = 400)

sysfonts::font_add_google("Oswald", family = "oswald")
showtext::showtext_auto()

basesize <- 30
# Regular plot theme
theme_flynn <- function(){ 
  
      theme_linedraw(base_size = basesize, base_family = "oswald") %+replace% 
        
        theme(plot.title = element_text(face = "bold", size = basesize * 1.3, hjust = 0, margin = margin(t = 0, b = 0.3, l = 0, r = 0, unit = "cm")),
              plot.subtitle = element_text(size = basesize),
              plot.caption = element_text(face = "italic", size = basesize * 0.6),
              strip.background = element_rect(fill = "gray80", color = "black"),
              strip.text = element_text(color = "black", face = "bold", margin = margin(t = 0.2, b = 0.2, l = 0.2, r = 0.2, unit = "cm")),
              panel.grid.major = element_line(color = "gray70", size = 0.15),
              panel.grid.minor = element_line(color = "gray90", size = 0.1),
              axis.title = element_text(face = "bold", size = basesize),
              axis.title.y = element_text(angle = 90, margin = margin(t = 0, r = 0.5, b = 0, l = 0, unit = "cm")),
              axis.title.x = element_text(margin = margin(t = 0.5, r = 0, b = 0, l = 0, unit = "cm")),
              axis.ticks = element_line(size = 0.1),
              axis.ticks.length = unit(0.1, "cm"),
              legend.title = element_text(face = "bold", hjust = 0, margin = margin(t = 0, b = 0, l = 0, r = 0, unit = "cm")),
              plot.margin = margin(0.5, 0.5, 0.5, 0.5, unit = "cm"),
              legend.margin=margin(t=-10, b=0, r=0, l=0),
              legend.box.margin=margin(-10,-10,-10,-10))
  }

# Map version of theme
theme_flynn_map <- function(){
  
  theme_void(base_family = "oswald") %+replace% 
    
    theme(plot.title = element_text(face = "bold", size = 18, hjust = 0, margin = margin(t = 0, b = 0.3, l = 0, r = 0, unit = "cm")),
          plot.subtitle = element_text(size = 12, hjust = 0, margin = margin(t = 0, b = 0.3, l = 0, r = 0, unit = "cm")),
          plot.caption = element_text(face = "italic", size = 8, hjust = 1, margin = margin(t = 0.2, unit = "cm")),
          plot.background = element_rect(fill = "white", color = "white"),
          strip.background = element_rect(fill = "gray80", color = "black"),
          strip.text = element_text(color = "black", face = "bold"),
          panel.grid.major = element_line(color = "white", size = 0),
          panel.grid.minor = element_line(color = "white", size = 0),
          #axis.title = element_text(face = "bold", size = 0),
          #axis.title.y = element_text(margin = margin(t = 0, r = 0.5, b = 0, l = 0, unit = "cm")),
          #axis.title.x = element_text(margin = margin(t = 0.5, r = 0, b = 0, l = 0, unit = "cm")),
          legend.title = element_text(face = "bold"),
          legend.position = "bottom",
          legend.key.height = unit(0.6, "cm"),
          legend.key.width = unit(2.5, "cm"))
}


# Set Seed
SEED <- 66502
set.seed(seed = SEED)

```



# Figures

```{r maps of deployments in 1950}


troop.data <- troopdata::get_troopdata(startyear = 1950, endyear = 1950) %>% 
  filter(ccode != 2) %>% 
  mutate(ccode = ifelse(ccode == 260, 255, ccode))


map.base <- rnaturalearth::ne_countries(returnclass = "sf")

map.1950 <- cshp(date = as.Date("1950-01-01")) %>%  
  dplyr::mutate(., ccode = countrycode::countrycode(gwcode, "gwn", "cown")) %>% 
  left_join(troop.data, by = "ccode")


ggplot() +
  geom_sf(data = map.base, aes(geometry = geometry), fill = "gray90", color = "gray90", size = 0.1) +
  geom_sf(data = map.1950, aes(geometry = geometry, fill = troops), color = "white", size = 0.1) +
  theme_flynn_map() +
  theme(legend.text = element_text(size = basesize*1.05, margin = margin(t = -6, unit = "pt")),
        legend.title = element_text(size = basesize*1.1, lineheight = 0.3),
        plot.margin = margin(0, 0, 0, 0)) +
  viridis::scale_fill_viridis(option = "magma", direction = 1, begin = 0.1, end = 0.9, na.value = "gray90", breaks = c(0, 20, 200, 2000, 20000, 200000), limits = c(0, 200000), trans = "log1p", label = comma_format()) +
  coord_sf(crs = st_crs("ESRI:54030")) +
  labs(fill = "Deployment\nSize")

ggsave(here("Figures/Chapter-Intro/figure-map-troops-1950.jpg"), width = 8, height = 5, units = "in")


```



```{r maps of deployments in 2020}


troop.data <- troopdata::get_troopdata(startyear = 2020, endyear = 2020) %>% 
  filter(ccode != 2) %>% 
  mutate(ccode = ifelse(ccode == 260, 255, ccode))


map.base <- rnaturalearth::ne_countries(returnclass = "sf")

map.2020 <- cshapes::cshp(date = as.Date("2019-01-01")) %>%  
  dplyr::mutate(., ccode = countrycode::countrycode(gwcode, "gwn", "cown")) %>% 
  left_join(troop.data, by = "ccode")


ggplot() +
  geom_sf(data = map.base, aes(geometry = geometry), fill = "gray90", color = "gray90", size = 0.1) +
  geom_sf(data = map.2020, aes(geometry = geometry, fill = troops), color = "white", size = 0.1) +
  theme_flynn_map() +
  theme(legend.text = element_text(size = basesize*1.05, margin = margin(t = -6, unit = "pt")),
        legend.title = element_text(size = basesize*1.1, lineheight = 0.3),
        plot.margin = margin(0, 0, 0, 0)) +
  viridis::scale_fill_viridis(option = "magma", direction = 1, begin = 0.1, end = 0.9, na.value = "gray90", breaks = c(0, 20, 200, 2000, 20000, 200000), limits = c(0, 200000), trans = "log1p", label = comma_format()) +
  coord_sf(crs = st_crs("ESRI:54030")) +
  labs(fill = "Deployment\nSize")

ggsave(here("Figures/Chapter-Intro/figure-map-troops-2020.jpg"), width = 8, height = 5, units = "in")


```

#Tables

```{r table for countries and years}

load("C:/Users/flynn/Dropbox/Projects/Minerva grant documents/Book/Data/General/opinion.data.RData")

table <- o.data %>% 
  group_by(country, year) %>% 
  dplyr::summarise(N = length(year)) %>% 
  pivot_wider(names_from = year,
              values_from = N) %>% 
  filter(!is.na(country)) %>% 
  dplyr::rename("Country" = "country") %>% 
  kable(booktabs = TRUE, format = "latex", caption = "Summary of countries surveyed and annual observation count") %>% 
  kable_styling(latex_options = c("striped", "repeat_header"), protect_latex = TRUE, font_size = 10) %>% 
  save_kable(here("Tables/Chapter-Intro/table-country-summary.tex"))


```
