```{r treatment models}
# Filter data to ensure complete cases on key variables
# Mostly needed this for stan approach
#p.data <- p.data %>% filter(!is.na(anti_us_protest) & !is.na(log_troops_z) & !is.na(log_troops_cumsum_z))


p.data <- read_csv(here::here("Data/Chapter-Protests/protest-data-final.csv")) %>% 
  group_by(ccode) %>% 
  mutate(log_troops_lag = lag(log_troops, order_by = year),
         troops_lag = lag(troops, order_by = year),
         anti_us_protest_lag = lag(anti_us_protest),
         troops_cumsum = log1p(lag(cumsum(troops), length = 2))) %>% 
  ungroup() %>% 
  mutate(log_troops_lag_z = arm::rescale(log_troops_lag),
         log_troops_z = arm::rescale(log_troops),
         log_troops_cumsum_z = arm::rescale(troops_cumsum)) %>% 
  group_by(year) %>% 
  mutate( troop.prop = troops/sum(troops, na.rm = TRUE))

# Do denominator first because it has the most restricted sample. To calculate the weights we need both numerator and denominator values.
ITER = 8000
WARMUP = 4000
CHAINS = 4
CORES = 4
SEED = 66502

get_prior(bf(troops ~ log_troops_lag + log_troops_cumsum_z + (1 | ccode),
                   hu ~ log_troops_lag + log_troops_cumsum_z + (1 | ccode)),
          family = hurdle_lognormal,
          nl = TRUE,
                   data = p.data)

PRIOR.N <- c(set_prior("normal(0,2)", class = "b"),
             set_prior("normal(1,2)", class = "Intercept"),
             set_prior("gamma(1,1)", class = "sd"),
             set_prior("gamma(1,1)", class = "sd", group = "ccode"),
             set_prior("gamma(1,1)", class = "sd", coef = "Intercept", group = "ccode"),
             set_prior("gamma(1,1)", class = "sigma"))

m.numerator <- brm(troops ~ log_troops_lag + log_troops_cumsum_z + (1 | ccode),
                   hu ~ log_troops_lag + log_troops_cumsum_z + (1 | ccode),
                   data = p.data,
                   prior = PRIOR.N,
                   family = hurdle_lognormal(),
                   iter = ITER,
                   warmup = WARMUP,
                   chains = CHAINS,
                   cores = CORES,
                   seed = SEED,
                   file_refit = "on_change",
                   save_model = here::here("Output/Chapter-Protests/model-numerator.stan"),
                   file = here::here("Output/Chapter-Protests/model-numerator"),
                   control = list(adapt_delta = 0.80,
                                          max_treedepth = 10),
                   backend = "cmdstanr")

num.check <- brms::pp_check(m.numerator)

# Adjustment set
# { Alignment[t], Ally[t], GDP[t], Growth[t-1], Population[t], ProtestEnvironment[t-1], Protest[t-1], Rebellion[t-1], Regime[t], Troops[t-1], USWar[t] }

get_prior(bf(troops ~ log_troops_lag + log_troops_cumsum_z + idealdistance_2_z + us_ally + gdp_z + gdp_growth_z + pop_z + log1p(protest_other) + anti_us_protest_lag + lag(conflict_dummy) + v2x_polyarchy_z + us_war + s(year) + (1 | ccode),
                      hu ~ log_troops_lag + log_troops_cumsum_z + idealdistance_2_z + us_ally + gdp_z + gdp_growth_z + pop_z + log1p(protest_other) + anti_us_protest_lag + lag(conflict_dummy) + v2x_polyarchy_z + us_war + s(year) + (1 | ccode)),
          family = hurdle_lognormal,
          nl = TRUE,
                   data = p.data)
  
PRIOR.D <- c(set_prior("normal(0,2)", class = "b"),
             set_prior("normal(1,2)", class = "Intercept"),
             set_prior("gamma(1,1)", class = "sd"),
             set_prior("gamma(1,1)", class = "sd", group = "ccode"),
             set_prior("gamma(1,1)", class = "sd", coef = "Intercept", group = "ccode"),
             set_prior("gamma(1,1)", class = "sigma"))

m.denominator <-  brm(troops ~ log_troops_lag + log_troops_cumsum_z + idealdistance_2_z + us_ally + gdp_z + gdp_growth_z + pop_z + log1p(protest_other) + anti_us_protest_lag + lag(conflict_dummy) + v2x_polyarchy_z + us_war + s(year, bs = "cr", k = 20) + (1 | ccode),
                      hu ~ log_troops_lag + log_troops_cumsum_z + idealdistance_2_z + us_ally + gdp_z + gdp_growth_z + pop_z + log1p(protest_other) + anti_us_protest_lag + lag(conflict_dummy) + v2x_polyarchy_z + us_war + s(year, bs = "cr", k = 20) + (1 | ccode),
                   data = p.data,
                   prior = PRIOR.D,
                   family = hurdle_lognormal(),
                   iter = ITER,
                   warmup = WARMUP,
                   chains = CHAINS,
                   cores = CORES,
                   seed = SEED,
                   file_refit = "on_change",
                   save_model = here::here("Output/Chapter-Protests/model-denominator.stan"),
                   file = here::here("Output/Chapter-Protests/model-denominator"),
                   control = list(adapt_delta = 0.80,
                                          max_treedepth = 10),
                   backend = "cmdstanr")
```


```{r generate draws for iptw weights}


# Set baseline stuff for loops
# Set number of draws for the length of the simulations
draws <- 2000
# Set the iptw truncation points. Basically generating an expontential shaped distribution
# and sampling from that so we're not grabbing as many extreme values.
iptw.trunc <- 50
# Set the hurdle value. This is the proportion of 0s in the data.
hu.val <- round(length(p.data$troops[p.data$troops==0])/length(p.data$troops), 2)

# Add posterior draws for numerator
post.n <- posterior_epred(m.numerator, newdata = p.data, allow_new_levels = TRUE, ndraws = draws) %>% 
  t() %>% 
  as_tibble(.names_repair = "universal") %>% 
  mutate(log_troops_z = p.data$log_troops_z,
         ccode = p.data$ccode,
         year = p.data$year,
         across(starts_with("V"),
                ~(brms::dhurdle_lognormal(x = log_troops_z,
                                          mu = .x,
                                          sigma = sd((log_troops_z - .x), na.rm = TRUE),
                                          hu = hu.val)),
                .names = "iptw_{.col}")) %>% 
  dplyr::select(starts_with("iptw")) # Remove everything except the posterior draws

# Check dimensions. Should be ~5000 rows to match rows in data
dim(post.n)

# Add posterior draws for denominator
post.d <- posterior_epred(m.denominator, newdata = p.data, allow_new_levels = TRUE, ndraws = draws) %>% 
  t() %>% 
  as_tibble(.names_repair = "universal") %>% 
  mutate(log_troops_z = p.data$log_troops_z,
         ccode = p.data$ccode,
         year = p.data$year,
         across(starts_with("V"),
                ~(brms::dhurdle_lognormal(x = log_troops_z,
                                          mu = .x,
                                          sigma = sd((log_troops_z - .x), na.rm = TRUE),
                                          hu = hu.val)),
                .names = "iptw_{.col}")) %>% 
  dplyr::select(starts_with("iptw")) # Remove everything except the posterior draws

dim(post.d)


# Create the iptw scores by dividing the numerator values by the denominator values
iptw.mat <- post.n/post.d 

iptw.mat <- iptw.mat %>%
  as_tibble() %>% 
  mutate(ccode = p.data$ccode,
         year = p.data$year,
         protest = p.data$anti_us_protest,
         log_troops_z = p.data$log_troops_z,
         log_troops_cumsum_z = p.data$log_troops_cumsum_z) %>% 
  group_by(ccode) %>% 
  mutate(across(.cols = starts_with("iptw"), ~replace(.x, is.na(.x), 1))) %>% 
  mutate(across(.cols = starts_with("diptw"), ~cumprod(.x))) %>% 
  ungroup() %>% 
  filter(!is.na(protest) & !is.na(log_troops_z) & !is.na(log_troops_cumsum_z)) %>% 
  dplyr::select(starts_with("iptw"))

# Create empty list
data.list <- list()

# Loop through the list to create separate data sets each with one column of iptw scores
i <- 1

for(i in 1:draws){
  data.list[[i]] <- p.data
  data.list[[i]]$iptw <- iptw.mat[,i]
}

# Go through the list and cap the iptw scores so things don't get crazy with
# huge values
data.list <- lapply(data.list, function(x) {
  
  cap.val <- iptw.trunc # Can use sample(iptw.trunc, 1) if using a vector of iptw values above
  temp <- x %>% 
    mutate(iptw = ifelse(iptw > cap.val, cap.val, iptw)) %>% 
    dplyr::select(ccode, anti_us_protest, anti_us_mil, log_troops_z, log_troops_cumsum_z, iptw) 
}
)

save(data.list, file = here("Data/Chapter-Protests/treatment-weight-stan-20211230.RData"))



```


```{r formula and prior, echo = FALSE}

# Outcome formula 1
ate.troops <- bf(anti_us_protest | weights(1) ~ log_troops_z + log_troops_cumsum_z + (1 | ccode))

# Outcome priors
PRIOR.ATE <- c(set_prior("student_t(3.5, 0, 1)", class = "b", coef = "log_troops_z"),
               set_prior("student_t(3.5, 0, 2)", class = "b", coef = "log_troops_cumsum_z"),
               set_prior("student_t(3.5, 0, 3)", class = "Intercept"))

```

```{r make stan code}
# DON'T TOUCH THIS OR ELSE YOU'LL HAVE TO EDIT THE STAN CODE BY HAND AGAIN!

make_stancode(formula = ate.troops,
              data = p.data.complete,
              prior = PRIOR.ATE,
              family = negbinomial(),
              save_model = here::here("Code/Chapter-Protests/troops-us-base-code.stan")
)

```

```{r use ate stan model}
# Have to add this to ensure there are only complete cases
p.data.complete <- p.data %>% filter(!is.na(anti_us_protest) & !is.na(log_troops_z) & !is.na(log_troops_cumsum_z)) %>% group_by(ccode) %>%  mutate(N = length(ccode),
                                                                                                                                                   Z = 1) 

# Convert modified stan code to c++
# Must modify by hand first to allow for changing weights
outcome_c <- stanc(here::here("Code/Chapter-Protests/troops-us-base-code.stan"),
                   allow_undefined = TRUE)

# Compile c++ stan to binary model object
outcome_model <- stan_model(
  stanc_ret = outcome_c,
  includes = paste0('\n#include "', here::here('Code/Chapter-Protests/iterfuns.hpp'), '"\n')
)

# Make dataset of all covariates and an intercept column
outcome_covariates <- model.matrix(~ log_troops_z + log_troops_cumsum_z, data = p.data.complete)

outcome_data <- list(
  N = nrow(p.data.complete),
  Y = p.data.complete$anti_us_protest,
  K = ncol(outcome_covariates),
  X = outcome_covariates,
  L = ncol(iptw.mat),
  N_1 = length(unique(p.data.complete$ccode)),
  M_1 = 1,
  J_1 = p.data.complete$N,
  Z_1_1 = p.data.complete$Z,
  IPW = as.matrix(iptw.mat),
  prior_only = 0
)

str(outcome_data)

outcome_samples <- sampling(
  outcome_model,
  data = outcome_data,
  chains = 8,
  iter = 2000,
  cores = 8,
  seed = 123
)
```